/* Generated by Reason Relay Compiler, PLEASE EDIT WITH CARE */

type document = {
  id: option(string),
  name: option(string),
  married: option(bool),
  age: option(int),
  closeRate: option(float),
};

type variablesType = Js.Dict.t(Js.Json.t);
let encodeVariables: unit => variablesType = () => Js.Dict.empty();

type schemaQueryResponse = SchemaTypes.document;
let decodeResponse = SchemaTypes.decodeQueryResponse;