/* Generated by Reason Relay Compiler, PLEASE EDIT WITH CARE */

type queryResponse = {
  id: string,
  name: string,
  married: bool,
  age: int,
  closeRate: float,
};

[@bs.module "./SchemaTypes.codec"]external decodeQueryResponse: Js.Json.t => queryResponse = "decodeQueryResponse";