/* Generated by Reason Relay Compiler, PLEASE EDIT WITH CARE */

type b = {
  id: string,
  iii: option(int),
};

type a = {
  id: string,
  ii: option(int),
  b: b,
  ff: float,
};

type c = {
  id: string,
  ss: option(string),
};

type document = {
  i: int,
  a: option(a),
  s: option(string),
  c: c,
};

[@bs.module "./SchemaTypes.codec"]external decodeQueryResponse: Js.Json.t => document = "decodeQueryResponse";