/* Generated by ReasonQL Compiler, PLEASE EDIT WITH CARE */

var decodeQueryResponse = function (res) {
  return [
    res.id,
    res.name,
    res.married,
    res.age,
    res.closeRate,
  ]
}

exports.decodeQueryResponse = decodeQueryResponse;